name: Cache Management
description: Used to get dependencies and saves cache
inputs:
  caching:
    description: 'Whether to use cache or not'
    required: false
    default: 'false'
runs:
  using: composite
  steps:
    - name: Cache dependencies
      id: cache
      if: inputs.caching != 'false'
      uses: actions/cache@v4
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching != 'true'
      run: npm ci
      shell: bash
