name: Cache Management
description: Used to get dependencies and saves cache
inputs:
  caching:
    description: 'Whether to use cache or not'
    required: false
    default: 'false'

outputs:
  used-cache:
    description: 'Cache used?'
    value: ${{ steps.install.outputs.cached }}

runs:
  using: composite
  steps:
    - name: Cache dependencies
      id: cache
      if: inputs.caching != 'false'
      uses: actions/cache@v4
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      id: install
      env:
        INPUT_CACHE: ${{inputs.caching}}
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching != 'true'
      run: |
        npm ci
        if[[ "$INPUT_CACHE" == "true" ]]; then
          echo "cached=true " >> $GITHUB_OUTPUT
        else
          echo "cached=false" >> $GITHUB_OUTPUT
        fi

      shell: bash
